package com.enjoy.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "LAST_MUSIC".
 */
@Entity
public class LastMusic {

    @Id
    private Long id;
    private Integer special_type;
    private String pic_huge;
    private String resource_type;
    private String pic_premium;
    private Integer havehigh;
    private String author;
    private String toneid;
    private Integer has_mv;
    private String song_id;
    private String piao_id;
    private String artist_id;
    private String lrclink;
    private String relate_status;
    private Integer learn;
    private String pic_big;
    private Integer play_type;
    private String album_id;
    private String album_title;
    private String bitrate_fee;
    private String song_source;
    private String all_artist_id;
    private String all_artist_ting_uid;
    private String all_rate;
    private Integer charge;
    private String copy_type;
    private Integer is_first_publish;
    private String korean_bb_song;
    private String pic_radio;
    private Integer has_mv_mobile;
    private String title;
    private String pic_small;
    private String album_no;
    private String resource_type_ext;
    private String ting_uid;
    private String file_link;

    @Generated
    public LastMusic() {
    }

    public LastMusic(Long id) {
        this.id = id;
    }

    @Generated
    public LastMusic(Long id, Integer special_type, String pic_huge, String resource_type, String pic_premium, Integer havehigh, String author, String toneid, Integer has_mv, String song_id, String piao_id, String artist_id, String lrclink, String relate_status, Integer learn, String pic_big, Integer play_type, String album_id, String album_title, String bitrate_fee, String song_source, String all_artist_id, String all_artist_ting_uid, String all_rate, Integer charge, String copy_type, Integer is_first_publish, String korean_bb_song, String pic_radio, Integer has_mv_mobile, String title, String pic_small, String album_no, String resource_type_ext, String ting_uid, String file_link) {
        this.id = id;
        this.special_type = special_type;
        this.pic_huge = pic_huge;
        this.resource_type = resource_type;
        this.pic_premium = pic_premium;
        this.havehigh = havehigh;
        this.author = author;
        this.toneid = toneid;
        this.has_mv = has_mv;
        this.song_id = song_id;
        this.piao_id = piao_id;
        this.artist_id = artist_id;
        this.lrclink = lrclink;
        this.relate_status = relate_status;
        this.learn = learn;
        this.pic_big = pic_big;
        this.play_type = play_type;
        this.album_id = album_id;
        this.album_title = album_title;
        this.bitrate_fee = bitrate_fee;
        this.song_source = song_source;
        this.all_artist_id = all_artist_id;
        this.all_artist_ting_uid = all_artist_ting_uid;
        this.all_rate = all_rate;
        this.charge = charge;
        this.copy_type = copy_type;
        this.is_first_publish = is_first_publish;
        this.korean_bb_song = korean_bb_song;
        this.pic_radio = pic_radio;
        this.has_mv_mobile = has_mv_mobile;
        this.title = title;
        this.pic_small = pic_small;
        this.album_no = album_no;
        this.resource_type_ext = resource_type_ext;
        this.ting_uid = ting_uid;
        this.file_link = file_link;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSpecial_type() {
        return special_type;
    }

    public void setSpecial_type(Integer special_type) {
        this.special_type = special_type;
    }

    public String getPic_huge() {
        return pic_huge;
    }

    public void setPic_huge(String pic_huge) {
        this.pic_huge = pic_huge;
    }

    public String getResource_type() {
        return resource_type;
    }

    public void setResource_type(String resource_type) {
        this.resource_type = resource_type;
    }

    public String getPic_premium() {
        return pic_premium;
    }

    public void setPic_premium(String pic_premium) {
        this.pic_premium = pic_premium;
    }

    public Integer getHavehigh() {
        return havehigh;
    }

    public void setHavehigh(Integer havehigh) {
        this.havehigh = havehigh;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getToneid() {
        return toneid;
    }

    public void setToneid(String toneid) {
        this.toneid = toneid;
    }

    public Integer getHas_mv() {
        return has_mv;
    }

    public void setHas_mv(Integer has_mv) {
        this.has_mv = has_mv;
    }

    public String getSong_id() {
        return song_id;
    }

    public void setSong_id(String song_id) {
        this.song_id = song_id;
    }

    public String getPiao_id() {
        return piao_id;
    }

    public void setPiao_id(String piao_id) {
        this.piao_id = piao_id;
    }

    public String getArtist_id() {
        return artist_id;
    }

    public void setArtist_id(String artist_id) {
        this.artist_id = artist_id;
    }

    public String getLrclink() {
        return lrclink;
    }

    public void setLrclink(String lrclink) {
        this.lrclink = lrclink;
    }

    public String getRelate_status() {
        return relate_status;
    }

    public void setRelate_status(String relate_status) {
        this.relate_status = relate_status;
    }

    public Integer getLearn() {
        return learn;
    }

    public void setLearn(Integer learn) {
        this.learn = learn;
    }

    public String getPic_big() {
        return pic_big;
    }

    public void setPic_big(String pic_big) {
        this.pic_big = pic_big;
    }

    public Integer getPlay_type() {
        return play_type;
    }

    public void setPlay_type(Integer play_type) {
        this.play_type = play_type;
    }

    public String getAlbum_id() {
        return album_id;
    }

    public void setAlbum_id(String album_id) {
        this.album_id = album_id;
    }

    public String getAlbum_title() {
        return album_title;
    }

    public void setAlbum_title(String album_title) {
        this.album_title = album_title;
    }

    public String getBitrate_fee() {
        return bitrate_fee;
    }

    public void setBitrate_fee(String bitrate_fee) {
        this.bitrate_fee = bitrate_fee;
    }

    public String getSong_source() {
        return song_source;
    }

    public void setSong_source(String song_source) {
        this.song_source = song_source;
    }

    public String getAll_artist_id() {
        return all_artist_id;
    }

    public void setAll_artist_id(String all_artist_id) {
        this.all_artist_id = all_artist_id;
    }

    public String getAll_artist_ting_uid() {
        return all_artist_ting_uid;
    }

    public void setAll_artist_ting_uid(String all_artist_ting_uid) {
        this.all_artist_ting_uid = all_artist_ting_uid;
    }

    public String getAll_rate() {
        return all_rate;
    }

    public void setAll_rate(String all_rate) {
        this.all_rate = all_rate;
    }

    public Integer getCharge() {
        return charge;
    }

    public void setCharge(Integer charge) {
        this.charge = charge;
    }

    public String getCopy_type() {
        return copy_type;
    }

    public void setCopy_type(String copy_type) {
        this.copy_type = copy_type;
    }

    public Integer getIs_first_publish() {
        return is_first_publish;
    }

    public void setIs_first_publish(Integer is_first_publish) {
        this.is_first_publish = is_first_publish;
    }

    public String getKorean_bb_song() {
        return korean_bb_song;
    }

    public void setKorean_bb_song(String korean_bb_song) {
        this.korean_bb_song = korean_bb_song;
    }

    public String getPic_radio() {
        return pic_radio;
    }

    public void setPic_radio(String pic_radio) {
        this.pic_radio = pic_radio;
    }

    public Integer getHas_mv_mobile() {
        return has_mv_mobile;
    }

    public void setHas_mv_mobile(Integer has_mv_mobile) {
        this.has_mv_mobile = has_mv_mobile;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getPic_small() {
        return pic_small;
    }

    public void setPic_small(String pic_small) {
        this.pic_small = pic_small;
    }

    public String getAlbum_no() {
        return album_no;
    }

    public void setAlbum_no(String album_no) {
        this.album_no = album_no;
    }

    public String getResource_type_ext() {
        return resource_type_ext;
    }

    public void setResource_type_ext(String resource_type_ext) {
        this.resource_type_ext = resource_type_ext;
    }

    public String getTing_uid() {
        return ting_uid;
    }

    public void setTing_uid(String ting_uid) {
        this.ting_uid = ting_uid;
    }

    public String getFile_link() {
        return file_link;
    }

    public void setFile_link(String file_link) {
        this.file_link = file_link;
    }

}
